version: '3.8'
services:
  java-app:
    build: .
    image: tarunsepta/java-sample-app:latest
    ports:
      - "8081:8081"
    depends_on:
      - mysql-db
      - redis-cache
    networks:
      appnet:
        aliases:
          - java-app
  mysql-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
    ports:
      - "3306:3306"
    networks:
      appnet:
        aliases:
          - db
  redis-cache:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      appnet:
        aliases:
          - redis
networks:
  appnet:
    driver: bridge